<?
	// KONSTANTA KODE KUITANSI
	if (!defined("AV_KASIR_KODE_KUITANSI_RJ")) define("AV_KASIR_KODE_KUITANSI_RJ","RJ");
	if (!defined("AV_KASIR_KODE_KUITANSI_RI")) define("AV_KASIR_KODE_KUITANSI_RI","RI");
	if (!defined("AV_KASIR_KODE_KUITANSI_UM")) define("AV_KASIR_KODE_KUITANSI_UM","UM");

	// KEWAJIBAN DEPOSIT
	if (!defined("AV_KASIR_KEWAJIBAN_DEPOSIT")) define("AV_KASIR_KEWAJIBAN_DEPOSIT","0,00");
?>